project.version=11.3.0+26.3
project.java=25
project.build-java=25
project.minecraft=26.3
# Forge and NeoForge artifacts are not available for Minecraft 26.3 yet.
project.enabled-loaders=fabric

mod.minecraft-range=>=26.3
mod.fabric-range=>=26.3
mod.forge-loader-range=[65,)
mod.neoforge-loader-range=[4,)
